= Logging
:experimental:

Cider Log Mode allows you to capture log events emitted by some of the
supported Java logging frameworks. The captured log events can be
searched, viewed in the Cider Inspector and Debugger as well as
streamed to clients.

== Usage

== Keybindings

|===
| Command | Keyboard shortcut | Description

| `cider-log`
| kbd:[C-c l l]
| Show the Cider log menu.

| `cider-log-appender`
| kbd:[C-c l a]
| Show the menu to manage appenders of a logging framework.

| `cider-log-consumer`
| kbd:[C-c l c]
| Show the menu to manage consumers listening to log events.

| `cider-log-event`
| kbd:[C-c l e]
| Show the menu to manage log events.
|===

== Supported log frameworks

Cider Log Mode supports log frameworks that allow reconfiguration at
run time. More specifically the framework should support attaching log
appenders to loggers, in order to capture events.

At the moment the following log frameworks are supported:

- https://docs.oracle.com/en/java/javase/19/core/java-logging-overview.html[Java Util Logging]
- https://logback.qos.ch[Logback]

There is some work in progress to support
https://logging.apache.org/log4j/2.x/[Log4j] as well, but there are
some https://stackoverflow.com/a/17842174/12711900[difficulties] with
configuration changes made at runtime, which are wiped out by the
Log4j2's reconfiguration mechanism.
